// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// hx711_reader //
// ------------ //

#define hx711_reader_wrap_target 3
#define hx711_reader_wrap 13

#define hx711_reader_HZ 10000000

static const uint16_t hx711_reader_program_instructions[] = {
    0xe020, //  0: set    x, 0                       
    0x8080, //  1: pull   noblock                    
    0x6020, //  2: out    x, 32                      
            //     .wrap_target
    0xe057, //  3: set    y, 23                      
    0x2020, //  4: wait   0 pin, 0                   
    0xe001, //  5: set    pins, 1                    
    0x4001, //  6: in     pins, 1                    
    0x1185, //  7: jmp    y--, 5          side 0 [1] 
    0x9880, //  8: pull   noblock         side 1     
    0x6020, //  9: out    x, 32                      
    0x1023, // 10: jmp    !x, 3           side 0     
    0xa041, // 11: mov    y, x                       
    0xe101, // 12: set    pins, 1                [1] 
    0x118c, // 13: jmp    y--, 12         side 0 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hx711_reader_program = {
    .instructions = hx711_reader_program_instructions,
    .length = 14,
    .origin = -1,
};

static inline pio_sm_config hx711_reader_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hx711_reader_wrap_target, offset + hx711_reader_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}


#include <assert.h>
#include <stddef.h>
#include "hardware/clocks.h"
#include "hardware/pio.h"
#include "hardware/structs/clocks.h"
#include "hx711.h"
void hx711_reader_pio_init(hx711_t* const hx) {
    assert(hx != NULL);
    assert(hx->_pio != NULL);
    pio_gpio_init(
        hx->_pio,
        hx->_clock_pin);
    //clock pin setup
    pio_sm_set_out_pins(
        hx->_pio,
        hx->_reader_sm,
        hx->_clock_pin,
        1);
    pio_sm_set_set_pins(
        hx->_pio,
        hx->_reader_sm,
        hx->_clock_pin,
        1);
    pio_sm_set_consecutive_pindirs(
        hx->_pio,
        hx->_reader_sm,
        hx->_clock_pin,
        1,
        true);
    //data pin setup
    pio_gpio_init(
        hx->_pio,
        hx->_data_pin);
    pio_sm_set_in_pins(
        hx->_pio,
        hx->_reader_sm,
        hx->_data_pin);
    pio_sm_set_consecutive_pindirs(
        hx->_pio,
        hx->_reader_sm,
        hx->_data_pin,
        1,
        false);
}
void hx711_reader_program_init(hx711_t* const hx) {
    assert(hx != NULL);
    assert(hx->_pio != NULL);
    pio_sm_config cfg = hx711_reader_program_get_default_config(
        hx->_reader_offset);
    const float div = (float)(clock_get_hz(clk_sys)) / (uint)hx711_reader_HZ;
    sm_config_set_clkdiv(
        &cfg,
        div);
    sm_config_set_set_pins(
        &cfg,
        hx->_clock_pin,
        1);
    sm_config_set_out_pins(
        &cfg,
        hx->_clock_pin,
        1);
    sm_config_set_sideset_pins(
        &cfg,
        hx->_clock_pin);
    sm_config_set_in_pins(
        &cfg,
        hx->_data_pin);
    sm_config_set_in_shift(
        &cfg,
        false,            //false = shift in left
        true,             //true = autopush enabled
        HX711_READ_BITS); //autopush on 24 bits
    pio_sm_clear_fifos(
        hx->_pio,
        hx->_reader_sm);
    //store a copy of the configuration for resetting the sm
    hx->_reader_prog_default_config = cfg;
}

#endif

