// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------- //
// motor_step_sequence //
// ------------------- //

#define motor_step_sequence_wrap_target 0
#define motor_step_sequence_wrap 6

static const uint16_t motor_step_sequence_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6004, //  1: out    pins, 4                    
    0xa027, //  2: mov    x, osr                     
    0x4024, //  3: in     x, 4                       
    0xa0e1, //  4: mov    osr, x                     
    0xa042, //  5: nop                               
    0x6004, //  6: out    pins, 4                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program motor_step_sequence_program = {
    .instructions = motor_step_sequence_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config motor_step_sequence_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + motor_step_sequence_wrap_target, offset + motor_step_sequence_wrap);
    sm_config_set_sideset(&c, 1, true, false);
    return c;
}

#include "hardware/pio.h"
static inline void motor_step_sequence_init(PIO pio, uint sm, uint offset, uint base_pin) {
    pio_sm_config c = motor_step_sequence_program_get_default_config(offset);
    sm_config_set_out_pins(&c, base_pin, 4);
    for (int i = 0; i < 4; i++) {
        pio_gpio_init(pio, base_pin + i); 
    }
    pio_sm_set_pindirs_with_mask(pio, sm, 0xF << base_pin, 0xF << base_pin);
    sm_config_set_clkdiv(&c, 1.f);
    pio_sm_init(pio, sm, offset, &c);   
    pio_sm_set_enabled(pio, sm, true);
}

#endif

